export type CommandResult = {
  stdout: string;
  stderr: string;
  exitCode: number;
};

export type FileEntry = { name: string; type: "file" | "directory" };

/** All file paths are relative to the workspace root. No browser state here. */
export interface Workspace {
  readonly kind: string;
  readFile(path: string): Promise<string>;
  writeFile(path: string, content: string): Promise<void>;
  listFiles(path?: string): Promise<FileEntry[]>;
  /** Optional: omit to expose a file-only workspace to the agent. */
  exec?(command: string): Promise<CommandResult>;
}

export type ToolDefinition = {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
};

export type ToolResult = { content: string; is_error: boolean };
export type ToolCall = { name: string; input: Record<string, unknown> };

export type AgentEvent =
  | { type: "text"; text: string }
  | { type: "tool"; name: string; summary: string }
  | { type: "tool_done"; name: string; isError: boolean }
  | { type: "idle" };

/** Generated by wasm-bindgen; inject it so this package owns no Wasm loader. */
export interface HostSession {
  send(prompt: string, onEvent: (raw: string) => void): Promise<void>;
  messages(): string;
  restoreMessages(json: string): void;
  setSystem(system: string): void;
  free(): void;
}

export interface HostSessionConstructor {
  new (
    url: string,
    model: string,
    headers: Record<string, string>,
    schemas: string,
    execute: (name: string, input: string) => Promise<string>,
  ): HostSession;
}
